name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
            ext: zip
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            ext: tar.gz
          - os: macos-15-intel
            platform: macos
            arch: x86_64
            ext: tar.gz
          - os: macos-latest
            platform: macos
            arch: arm64
            ext: tar.gz

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Get tag version and OIDN version
        id: get_versions
        run: |
          . .github/workflows/scripts/get_versions.sh
        shell: bash

      - name: Download OIDN
        run: |
          . .github/workflows/scripts/download_oidn.sh
        env:
          # Use OIDN version here for test
          OIDN_VERSION: ${{ env.OIDN_VERSION }}
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
        shell: bash

      - name: Build and test
        env:
          VERSION: ${{ env.OIDN_VERSION }}
          PLATFORM: ${{ matrix.platform }}
        run: |
          . .github/workflows/scripts/build.sh
          . .github/workflows/scripts/run_tests.sh
        shell: bash
        continue-on-error: false
